package ArduinoTestLanguage.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;
  public static Object propertyMacro_GetPropertyValue_5379103421905083660(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b2275eL, 0x4aa66a1000bbb6feL, "initState")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5379103421904838637(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L, 0x4aa66a1000b226f6L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_5379103421905371941(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(_context.getNode(), MetaAdapterFactory.getProperty(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L, 0x4aa66a1000b226f6L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_5379103421905108611(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb53bL, 0x4aa66a1000bbb5f7L, "actuator")), MetaAdapterFactory.getProperty(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L, 0x4aa66a1000b226f6L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_5379103421905116038(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean_def(_context.getNode(), MetaAdapterFactory.getProperty(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb53bL, 0x4aa66a1000bbb5e6L, "status"), "true") ? "HIGH" : "LOW");
  }
  public static Object propertyMacro_GetPropertyValue_5379103421905186248(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb619L, 0x4aa66a1000bbb67cL, "sensor")), MetaAdapterFactory.getProperty(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L, 0x4aa66a1000b226f6L, "pin"));
  }
  public static Object propertyMacro_GetPropertyValue_5379103421905193564(final PropertyMacroContext _context) {
    return (SPropertyOperations.getBoolean_def(_context.getNode(), MetaAdapterFactory.getProperty(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb619L, 0x4aa66a1000bbb668L, "status"), "true") ? "HIGH" : "LOW");
  }
  public static Object propertyMacro_GetPropertyValue_5379103421905559338(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getReferenceLink(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb619L, 0x4aa66a1000bbb691L, "target")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static Object propertyMacro_GetPropertyValue_5379103421905213441(final PropertyMacroContext _context) {
    return "" + _context.getSessionObject("current_state_name");
  }
  public static Object propertyMacro_GetPropertyValue_5379103421905254934(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"));
  }
  public static SNode sourceNodeQuery_5379103421905351013(final SourceSubstituteMacroNodeContext _context) {
    _context.putSessionObject("current_state_name", SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    return SLinkOperations.getTarget(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb4efL, 0x4aa66a1000bc2209L, "transitions"));
  }
  public static Iterable<SNode> sourceNodesQuery_5379103421904900178(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b2275eL, 0x4aa66a1000b22771L, "bricks"));
  }
  public static Iterable<SNode> sourceNodesQuery_5379103421905345517(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b2275eL, 0x4aa66a1000bbb6bcL, "states"));
  }
  public static Iterable<SNode> sourceNodesQuery_5379103421905349238(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb4efL, 0x4aa66a1000bc21efL, "actions"));
  }
}
