package ArduinoTestLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum STATUS {
  high("high", true),
  low("low", false);

  private String myName;
  public String getName() {
    return this.myName;
  }
  public String getValueAsString() {
    return "" + this.myValue;
  }
  public static List<STATUS> getConstants() {
    List<STATUS> list = ListSequence.fromList(new LinkedList<STATUS>());
    ListSequence.fromList(list).addElement(STATUS.high);
    ListSequence.fromList(list).addElement(STATUS.low);
    return list;
  }
  public static STATUS getDefault() {
    return STATUS.high;
  }
  public static STATUS parseValue(String value) {
    if (value == null) {
      return STATUS.getDefault();
    }
    if (value.equals(STATUS.high.getValueAsString())) {
      return STATUS.high;
    }
    if (value.equals(STATUS.low.getValueAsString())) {
      return STATUS.low;
    }
    return STATUS.getDefault();
  }
  private boolean myValue;
  STATUS(String name, boolean value) {
    this.myName = name;
    this.myValue = value;
  }
  public boolean getValue() {
    return this.myValue;
  }
}
