package ArduinoTestLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAction = new ConceptDescriptorBuilder("ArduinoTestLanguage.structure.Action", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb53bL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(5379103421904958950L, "status")).properties("status").referenceDescriptors(new ConceptDescriptorBuilder.Ref(5379103421904958967L, "actuator", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b2272dL), false)).references("actuator").create();
  /*package*/ final ConceptDescriptor myConceptActuator = new ConceptDescriptorBuilder("ArduinoTestLanguage.structure.Actuator", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b2272dL)).super_("ArduinoTestLanguage.structure.Brick").super_(MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L)).parents("ArduinoTestLanguage.structure.Brick").parentIds(MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L)).create();
  /*package*/ final ConceptDescriptor myConceptApp = new ConceptDescriptorBuilder("ArduinoTestLanguage.structure.App", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b2275eL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.execution.util.structure.IMainClass", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(5379103421904959230L, "initState", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb4efL), false)).references("initState").childDescriptors(new ConceptDescriptorBuilder.Link(5379103421904332657L, "bricks", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L), false, true, false), new ConceptDescriptorBuilder.Link(5379103421904959164L, "states", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb4efL), false, true, false)).children(new String[]{"bricks", "states"}, new boolean[]{true, true}).create();
  /*package*/ final ConceptDescriptor myConceptBrick = new ConceptDescriptorBuilder("ArduinoTestLanguage.structure.Brick", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(5379103421904332534L, "pin")).properties("pin").abstract_().create();
  /*package*/ final ConceptDescriptor myConceptSensor = new ConceptDescriptorBuilder("ArduinoTestLanguage.structure.Sensor", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b2274cL)).super_("ArduinoTestLanguage.structure.Brick").super_(MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L)).parents("ArduinoTestLanguage.structure.Brick").parentIds(MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b16c52L)).create();
  /*package*/ final ConceptDescriptor myConceptState = new ConceptDescriptorBuilder("ArduinoTestLanguage.structure.State", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb4efL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(5379103421904986607L, "actions", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb53bL), true, true, false), new ConceptDescriptorBuilder.Link(5379103421904986633L, "transitions", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb619L), false, false, false)).children(new String[]{"actions", "transitions"}, new boolean[]{true, false}).create();
  /*package*/ final ConceptDescriptor myConceptTransition = new ConceptDescriptorBuilder("ArduinoTestLanguage.structure.Transition", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb619L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(5379103421904959080L, "status")).properties("status").referenceDescriptors(new ConceptDescriptorBuilder.Ref(5379103421904959100L, "sensor", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000b2274cL), false), new ConceptDescriptorBuilder.Ref(5379103421904959121L, "target", MetaIdFactory.conceptId(0xcd609ef6a120482eL, 0xbf80d86e6435a6ccL, 0x4aa66a1000bbb4efL), false)).references("sensor", "target").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptActuator, myConceptApp, myConceptBrick, myConceptSensor, myConceptState, myConceptTransition);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0l, conceptFqName)) {
      case 0:
        return myConceptAction;
      case 1:
        return myConceptActuator;
      case 2:
        return myConceptApp;
      case 3:
        return myConceptBrick;
      case 4:
        return myConceptSensor;
      case 5:
        return myConceptState;
      case 6:
        return myConceptTransition;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0l = new String[]{"ArduinoTestLanguage.structure.Action", "ArduinoTestLanguage.structure.Actuator", "ArduinoTestLanguage.structure.App", "ArduinoTestLanguage.structure.Brick", "ArduinoTestLanguage.structure.Sensor", "ArduinoTestLanguage.structure.State", "ArduinoTestLanguage.structure.Transition"};
}
