package ArduinoTestLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 1:
        return new Actuator_BehaviorDescriptor();
      case 3:
        return new Sensor_BehaviorDescriptor();
      case 2:
        return new App_BehaviorDescriptor();
      case 4:
        return new State_BehaviorDescriptor();
      case 0:
        return new Action_BehaviorDescriptor();
      case 5:
        return new Transition_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"ArduinoTestLanguage.structure.Action", "ArduinoTestLanguage.structure.Actuator", "ArduinoTestLanguage.structure.App", "ArduinoTestLanguage.structure.Sensor", "ArduinoTestLanguage.structure.State", "ArduinoTestLanguage.structure.Transition"};
}
