package ArduinoTestLanguage.behavior;

/*Generated by MPS */


public class Sensor_BehaviorDescriptor extends Brick_BehaviorDescriptor {
  public Sensor_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ArduinoTestLanguage.structure.Sensor";
  }
}
